#include "seele_shader.h"
#include <algorithm>
#include <sstream>

namespace te::hackgu {

void SeeleShaderGenerator::initialize() {
    m_setup_common_defines();
}

void SeeleShaderGenerator::m_setup_common_defines() {
    m_defines = {
        "#define USE_PBR",
        "#define USE_TEXCOORDS",
        "#define USE_NORMALS",
        "#define MAX_LIGHTS 4",
        "#define PI 3.14159265"
    };
}

std::string SeeleShaderGenerator::generate_pbr_shader(
    const std::string& vertex_defines,
    const std::string& fragment_defines
) {
    std::string shader = R"(
// ========================================
// TWILIGHT ELYSIA // PBR SHADER
// Generated by Seele AI :: Data-Born Rendering
// ========================================

)";

    shader += vertex_defines + '\n';
    
    // Vertex shader
    shader += R"(
#version 460
layout(location = 0) in vec3 in_pos;
layout(location = 1) in vec3 in_normal;
layout(location = 2) in vec2 in_uv;

layout(location = 0) out vec3 v_world_pos;
layout(location = 1) out vec3 v_normal;
layout(location = 2) out vec2 v_uv;
layout(location = 3) out vec3 v_view_dir;

uniform mat4 u_model;
uniform mat4 u_view;
uniform mat4 u_proj;
uniform mat3 u_normal_mat;

void main() {
    vec4 world_pos = u_model * vec4(in_pos, 1.0);
    v_world_pos = world_pos.xyz;
    v_normal = u_normal_mat * in_normal;
    v_uv = in_uv;
    v_view_dir = normalize(u_view[3].xyz - world_pos.xyz);
    
    gl_Position = u_proj * u_view * world_pos;
}
)";

    shader += fragment_defines + '\n';
    
    // Fragment shader
    shader += R"(
#version 460
layout(location = 0) in vec3 v_world_pos;
layout(location = 1) in vec3 v_normal;
layout(location = 2) in vec2 v_uv;
layout(location = 3) in vec3 v_view_dir;

layout(location = 0) out vec4 out_color;

uniform vec3 u_albedo;
uniform float u_metallic;
uniform float u_roughness;
uniform vec3 u_light_pos;
uniform vec3 u_light_color;
uniform sampler2D u_albedo_map;
uniform sampler2D u_normal_map;
uniform sampler2D u_metallic_map;
uniform sampler2D u_roughness_map;

const vec3 LIGHT_COLOR = vec3(1.0, 0.95, 0.85);

void main() {
    vec3 N = normalize(v_normal);
    vec3 L = normalize(u_light_pos - v_world_pos);
    vec3 V = normalize(v_view_dir);
    vec3 H = normalize(L + V);
    
    float NdotL = max(dot(N, L), 0.0);
    float NdotV = max(dot(N, V), 0.0);
    float NdotH = max(dot(N, H), 0.0);
    float VdotH = max(dot(V, H), 0.0);
    
    // Calculate Fresnel (Schlick approximation)
    vec3 F0 = mix(vec3(0.04), u_albedo, u_metallic);
    vec3 F = F0 + (1.0 - F0) * pow(1.0 - VdotH, 5.0);
    
    // Cook-Torrance BRDF
    float D = NdotH * u_roughness;  // Simplified
    float G = 1.0;  // Simplified
    vec3 numerator = D * G * F;
    float denominator = 4.0 * NdotV * NdotL + 0.0001;
    vec3 specular = numerator / denominator;
    
    // Lambert diffuse
    vec3 kS = F;
    vec3 kD = vec3(1.0) - kS;
    kD *= 1.0 - u_metallic;
    
    vec3 fresnel = LIGHT_COLOR * NdotL;
    vec3 diffuse = kD * u_albedo / 3.14159;
    
    out_color = vec4(diffuse + specular, 1.0);
}
)";
    
    return shader;
}

std::string SeeleShaderGenerator::generate_corruption_shader(float corruption_level) {
    std::string shader = R"(
// ========================================
// CORRUPTION DATA SHADER
// Red static overlay for infected zones
// ========================================

#version 460
)";

    std::string frag = R"(
layout(location = 0) in vec3 v_world_pos;
layout(location = 1) in vec3 v_normal;
layout(location = 2) in vec2 v_uv;

layout(location = 0) out vec4 out_color;

uniform sampler2D u_base_color;
uniform float u_corruption;
uniform float u_time;

float hash(vec2 p) {
    return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453);
}

void main() {
    vec3 base = texture(u_base_color, v_uv * vec2(256.0)).rgb;
    
    // Screen-space noise for corruption
    vec2 noise_uv = v_uv * 32.0 + vec2(u_time * 2.0);
    float noise = hash(noise_uv);
    
    // Red channel modulation
    float corruption_mask = step(0.5, noise * u_corruption * 2.0);
    base.r += corruption_mask * 0.5;
    base.g *= 0.5 - corruption_mask * 0.3;
    base.b *= 0.5 - corruption_mask * 0.3;
    
    // Pulsing effect
    float pulse = sin(u_time * 5.0) * 0.1 + 0.9;
    base *= pulse;
    
    out_color = vec4(base, 1.0);
}
)";
    
    shader += frag;
    return shader;
}

std::string SeeleShaderGenerator::generate_toon_shader() {
    return R"(
// ========================================
// TOON SHADING - .hack CHARACTER STYLE
//========================================
#version 460
layout(location = 0) in vec3 in_pos;
layout(location = 1) in vec3 in_normal;
layout(location = 2) in vec2 in_uv;
layout(location = 0) out vec3 v_normal;
layout(location = 1) out vec2 v_uv;
uniform mat4 u_model, u_view, u_proj;
uniform mat3 u_normal_mat;
void main() {
    v_normal = u_normal_mat * in_normal;
    v_uv = in_uv;
    gl_Position = u_proj * u_view * u_model * vec4(in_pos, 1.0);
}

#version 460
layout(location = 0) in vec3 v_normal;
layout(location = 1) in vec2 v_uv;
layout(location = 0) out vec4 out_color;
uniform vec3 u_light_dir;
uniform vec3 u_base_color;
uniform sampler2D u_texture;

void main() {
    float ndotl = dot(v_normal, normalize(u_light_dir));
    float intensity = floor(ndotl * 4.0) / 4.0 + 0.1;
    vec3 color = u_base_color * texture(u_texture, v_uv).rgb;
    out_color = vec4(color * intensity, 1.0);
}
)";
}

std::string SeeleShaderGenerator::generate_world_shader(
    const std::string& environment,
    float corruption
) {
    if (environment.find("cyber") != std::string::npos || 
        environment.find("delta") != std::string::npos) {
        return generate_corruption_shader(corruption);
    }
    return generate_pbr_shader();
}

WorldData SeeleShaderGenerator::generate_world_chunk(
    const std::string& district,
    int chunk_x, int chunk_z,
    float corruption_level
) {
    WorldData world;
    world.world_name = "TWORLD_" + district;
    world.server_name = "R2_" + district;
    world.district = district;
    world.corruption_level = corruption_level;
    
    WorldChunk chunk;
    chunk.chunk_id = district + "_chunk_" + std::to_string(chunk_x) + "_" + std::to_string(chunk_z);
    chunk.x = chunk_x;
    chunk.z = chunk_z;
    chunk.corruption_level = corruption_level;
    
    // Generate material presets based on environment
    if (district.find("mac_anu") != std::string::npos ||
        district.find("central") != std::string::npos) {
        // Urban/city environment
        chunk.width = 32;
        chunk.depth = 32;
        chunk.height_scale = 1.0f;
    } else if (district.find("delta") != std::string::npos) {
        // Dungeon environment
        chunk.width = 16;
        chunk.depth = 16;
        chunk.height_scale = 0.5f;
    } else if (district.find("data_realm") != std::string::npos) {
        // Corrupted data realm
        chunk.width = 24;
        chunk.depth = 24;
        chunk.height_scale = 2.0f;
    }
    
    world.chunks.push_back(chunk);
    return world;
}

MaterialPreset SeeleShaderGenerator::generate_material(
    const std::string& description,
    const std::string& asset_path
) {
    MaterialPreset mat;
    mat.name = description;
    mat.asset_path = asset_path;
    
    if (description.find("metal") != std::string::npos ||
        description.find("blade") != std::string::npos ||
        description.find("weapon") != std::string::npos) {
        mat.metallic = 0.8f;
        mat.roughness = 0.3f;
        mat.albedo_path = asset_path;
    } else if (description.find("organic") != std::string::npos ||
               description.find("tree") != std::string::npos ||
               description.find("nature") != std::string::npos) {
        mat.metallic = 0.0f;
        mat.roughness = 0.7f;
    } else {
        mat.roughness = 0.5f;
    }
    
    mat.ao = 1.0f;
    return mat;
}

MaterialPreset SeeleShaderGenerator::apply_corruption(
    const MaterialPreset& source,
    float corruption_level
) {
    MaterialPreset corrupted = source;
    corrupted.metallic *= (1.0f - corruption_level * 0.5f);
    corrupted.roughness *= (1.0f + corruption_level * 0.3f);
    return corrupted;
}

} // namespace te::hackgu